# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-06 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0023_auto_20200304_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='commencement_date',
            field=models.DateField(blank=True, null=True, verbose_name='Commencement Date'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='film_purpose',
            field=models.CharField(blank=True, choices=[('education', 'Eductaion'), ('advertising', 'Advertising'), ('feature_film', 'Feature film'), ('recreation', 'Recreation'), ('other', 'other')], max_length=40, null=True, verbose_name='Purpose of Film'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='film_purpose_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='film_type',
            field=models.CharField(blank=True, choices=[('motion_film', 'Motion film'), ('photography', 'Photography')], max_length=40, null=True, verbose_name='Type of Film'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='film_usage',
            field=models.CharField(blank=True, choices=[('sell', 'Sell on to a third pary, e.g. image library, publisher'), ('editorial', 'Editorial'), ('advertising', 'Advertising'), ('other', 'Other')], max_length=40, null=True, verbose_name='Film be used'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='film_usage_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='previous_contact_person',
            field=models.CharField(max_length=100, null=True, verbose_name='Previous Contact person'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='production_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='sponsorship',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'other')], max_length=40, null=True, verbose_name='Sponsorship Type'),
        ),
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='sponsorship_details',
            field=models.TextField(blank=True),
        ),
    ]
