# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0024_auto_20200306_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalFilmingParks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_of_interest', models.CharField(blank=True, max_length=100, null=True, verbose_name='Feture of interest')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filming_proposal', to='commercialoperator.Park')),
                ('proposal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filming_parks', to='commercialoperator.Proposal')),
            ],
        ),
    ]
