# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0025_proposalfilmingparks'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='assistance_staff_capacity',
            field=models.TextField(blank=True, verbose_name='Capacity of staff for assistance'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='camp_location',
            field=models.TextField(blank=True, verbose_name='Where'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='camp_on_land',
            field=models.BooleanField(default=False, verbose_name='Camp on CALM land'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='cultural_significance',
            field=models.BooleanField(default=False, verbose_name='Areas of cultural significance'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='cultural_significance_details',
            field=models.TextField(blank=True, verbose_name='Cultural significance details'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='film_staff_capacity',
            field=models.TextField(blank=True, verbose_name='Capacity of staff for filming'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='no_of_people',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Activity title'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='off_road',
            field=models.BooleanField(default=False, verbose_name='Conduct any off-road activity'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='off_road_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='road_closure',
            field=models.BooleanField(default=False, verbose_name='roads to be closed during filming'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='road_closure_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='staff_assistance',
            field=models.BooleanField(default=False, verbose_name='Need assistance from Department staff'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='staff_to_film',
            field=models.BooleanField(default=False, verbose_name='Need Department staff to film'),
        ),
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='track_use',
            field=models.BooleanField(default=False, verbose_name='Use of Tracks or trails'),
        ),
    ]
