# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0026_auto_20200306_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfilmingparks',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filming_parks', to='commercialoperator.Proposal'),
        ),
    ]
