# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-20 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0028_filmingparkdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='alteration_required',
            field=models.BooleanField(default=False, verbose_name='Any alteration required to the area'),
        ),
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='other_equipments',
            field=models.TextField(blank=True, null=True, verbose_name='Number and type of cameras to be used'),
        ),
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='rps_overweight',
            field=models.BooleanField(default=False, verbose_name='Weight of RPS over two kg'),
        ),
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='rps_used',
            field=models.BooleanField(default=False, verbose_name='Use of RPS for filming'),
        ),
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='vehicle_owned',
            field=models.BooleanField(default=False, verbose_name='Vehicle Hired on owned'),
        ),
    ]
