# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-23 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0029_auto_20200320_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='activity_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Activity title'),
        ),
    ]
