# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-01 07:10
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0030_auto_20200323_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='film_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('motion_film', 'Motion film'), ('photography', 'Photography')], max_length=40, null=True, verbose_name='Type of Film'),
        ),
    ]
