# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-02 01:08
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0031_auto_20200401_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='film_purpose',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('education', 'Eductaion'), ('advertising', 'Advertising'), ('feature_film', 'Feature film'), ('recreation', 'Recreation'), ('other', 'other')], max_length=200, null=True, verbose_name='Purpose of Film'),
        ),
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='film_usage',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sell', 'Sell on to a third pary, e.g. image library, publisher'), ('editorial', 'Editorial'), ('advertising', 'Advertising'), ('other', 'Other')], max_length=160, null=True, verbose_name='Film be used'),
        ),
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='sponsorship',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'other')], max_length=120, null=True, verbose_name='Sponsorship Type'),
        ),
    ]
