# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-02 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0032_auto_20200402_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='sponsorship',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('other', 'other')], max_length=40, null=True, verbose_name='Sponsorship Type'),
        ),
    ]
