# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-03 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercialoperator', '0034_districtproposal_districtproposalapprovergroup_districtproposalassessorgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictProposalDeclinedDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('cc_email', models.TextField(null=True)),
                ('district_proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.DistrictProposal')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
