# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-09 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0036_auto_20200406_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalEventsParks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', models.ManyToManyField(to='commercialoperator.Activity')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_proposal', to='commercialoperator.Park')),
                ('proposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_parks', to='commercialoperator.Proposal')),
            ],
        ),
        migrations.AlterField(
            model_name='districtproposal',
            name='proposal_park',
            field=models.ManyToManyField(to='commercialoperator.ProposalFilmingParks'),
        ),
    ]
