# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-16 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0039_abseilingclimbingactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ApplicationType'),
        ),
    ]
