# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-18 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0040_question_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventotherdetails',
            name='officials_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='proposaleventotherdetails',
            name='participants_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='proposaleventotherdetails',
            name='support_vehicle_number',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
