# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-04-30 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0043_preeventsparkdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='approvals_gained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='approvals_gained_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='emergency_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='equipment_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='event_management_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='media_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='media_involved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='num_officials',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of officials expected'),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='num_spectators',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of spectators expected'),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='num_vehicles',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of vehicles expected'),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='other_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='risk_managment_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='rubbish_removal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='rubbish_removal_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='structure_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='structure_change_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='toilets_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='toilets_provided_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='traffic_management_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='vendor_hired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='vendor_hired_details',
            field=models.TextField(blank=True),
        ),
    ]
