# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-01 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0044_auto_20200430_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposaleventmanagement',
            old_name='risk_managment_plan',
            new_name='risk_management_plan',
        ),
    ]
