# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-01 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0045_auto_20200501_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventactivities',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposaleventactivities',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
