# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-06 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0047_auto_20200504_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ApplicationType'),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='fee_invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
