# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-06 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0048_auto_20200506_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='application_type',
        ),
        migrations.AddField(
            model_name='proposalstandardrequirement',
            name='application_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.ApplicationType'),
        ),
        migrations.AddField(
            model_name='proposalstandardrequirement',
            name='participant_number_required',
            field=models.BooleanField(default=False),
        ),
    ]
