# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-06 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0049_auto_20200506_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalstandardrequirement',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
