# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0050_proposalstandardrequirement_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='fee_invoice_reference',
        ),
        migrations.AddField(
            model_name='compliance',
            name='fee_invoice_reference',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
