# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0051_auto_20200511_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='filming_approval_type',
            field=models.CharField(choices=[('lawful_autority', 'Lawful Authority'), ('licence', 'Licence')], default='Lawful Authority', max_length=30, verbose_name='Filming Approval Type'),
        ),
    ]
