# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0058_auto_20200605_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtapproval',
            name='licence_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_licence_document', to='commercialoperator.ApprovalDocument'),
        ),
        migrations.AddField(
            model_name='districtapproval',
            name='renewal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_renewal_document', to='commercialoperator.ApprovalDocument'),
        ),
    ]
