# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-12 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0059_auto_20200611_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtproposal',
            name='district_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commercialoperator.DistrictApproval'),
        ),
    ]
