# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-15 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0060_districtproposal_district_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='district_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_compliance', to='commercialoperator.DistrictProposal'),
        ),
    ]
