# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-17 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0061_compliance_district_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='district_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_compliance', to='commercialoperator.DistrictApproval'),
        ),
    ]
