# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-29 13:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0061_compliancefee_compliancefeeinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliance',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
