# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-13 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0062_compliance_district_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_requirements', to='commercialoperator.District'),
        ),
    ]
