# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0062_compliance_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compliance',
            name='meta',
        ),
        migrations.AddField(
            model_name='compliance',
            name='num_participants',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Number of participants'),
        ),
    ]
