# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-06-30 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0063_auto_20200630_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='events_park_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
