# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-02 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0064_auto_20200630_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='filming_fee_4days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming 4 Days or more Fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='filming_fee_full_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming Full Day Fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='filming_fee_half_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming Half Day Fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='filming_fee_subsequent_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming Full Day Fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Application Fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='events_park_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Events Park Fee (per participant, per park)'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='licence_fee_1yr',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='T Class Licence Fee (1 Year)'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='licence_fee_2mth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='T Class Licence Fee (2 Months)'),
        ),
    ]
