# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-03 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0066_auto_20200702_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmingfee',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filming_fees', to='commercialoperator.Proposal'),
        ),
    ]
