# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-04 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0068_proposalfilmingactivity_half_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationtype',
            name='photography_fee_4days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography 4 days or more fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='photography_fee_full_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photoraphy full day fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='photography_fee_half_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography half day fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='photography_fee_subsequent_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography full day fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='filming_fee_4days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming 4 days or more fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='filming_fee_full_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming full day fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='filming_fee_half_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming half day fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='filming_fee_subsequent_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming full day fee'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'extended'), ('awaiting_payment', 'Awaiting Payment')], default='current', max_length=40),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='customer_status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'Under Review'), ('amendment_required', 'Amendment Required'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined'), ('awaiting_payment', 'Awaiting Payment')], default='draft', max_length=40, verbose_name='Customer Status'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='processing_status',
            field=models.CharField(choices=[('temp', 'Temporary'), ('draft', 'Draft'), ('with_assessor', 'With Assessor'), ('with_district_assessor', 'With District Assessor'), ('on_hold', 'On Hold'), ('with_qa_officer', 'With QA Officer'), ('with_referral', 'With Referral'), ('with_assessor_requirements', 'With Assessor (Requirements)'), ('with_approver', 'With Approver'), ('renewal', 'Renewal'), ('licence_amendment', 'Licence Amendment'), ('awaiting_applicant_respone', 'Awaiting Applicant Response'), ('awaiting_assessor_response', 'Awaiting Assessor Response'), ('awaiting_responses', 'Awaiting Responses'), ('ready_for_conditions', 'Ready for Conditions'), ('ready_to_issue', 'Ready to Issue'), ('approved', 'Approved'), ('declined', 'Declined'), ('discarded', 'Discarded'), ('partially_approved', 'Partially Approved'), ('partially_declined', 'Partially Declined'), ('awaiting_payment', 'Awaiting Payment')], default='draft', max_length=30, verbose_name='Processing Status'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
