# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-06 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0069_auto_20200704_1818'),
        ('commercialoperator', '0062_compliance_district_approval'),
        ('commercialoperator', '0021_auto_20200603_1642'),
    ]

    operations = [
    ]
