# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-19 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0070_merge_20200707_0104'),
        ('commercialoperator', '0063_proposalrequirement_district'),
    ]

    operations = [
    ]
