# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-28 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0071_merge_20200719_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventsparks',
            name='event_activities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='applicationfee',
            name='expiry_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='filming_fee_subsequent_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming subsequent day fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='photography_fee_subsequent_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography subsequent day fee'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expiry_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class'), ('Event', 'Event'), ('Filming', 'Filming')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
