# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-29 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0072_auto_20200728_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposaleventsparks',
            name='activities',
        ),
    ]
