# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-07-29 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0073_remove_proposaleventsparks_activities'),
        ('commercialoperator', '0072_auto_20200724_1522'),
    ]

    operations = [
    ]
