# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-05 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0074_merge_20200729_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('credit_facility_link', 'Credit Facility Link'), ('deed_poll', 'Deed poll'), ('online_training_document', 'Online Training Document'), ('park_finder_link', 'Park Finder Link'), ('fees_and_charges', 'Fees and charges link')], max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='film_purpose',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('education', 'Education'), ('advertising', 'Advertising'), ('feature_film', 'Feature film'), ('recreation', 'Recreation'), ('documentary', 'Documentary'), ('tourism', 'Tourism'), ('other', 'other')], max_length=200, null=True, verbose_name='Purpose of Film'),
        ),
    ]
