# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-05 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0075_auto_20200805_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingaccess',
            name='track_use_details',
            field=models.TextField(blank=True),
        ),
    ]
