# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-06 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0077_auto_20200806_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='alteration_required_details',
            field=models.TextField(blank=True, null=True, verbose_name='Alteration required details'),
        ),
        migrations.AlterField(
            model_name='proposalfilmingequipment',
            name='other_equipments',
            field=models.TextField(blank=True, null=True, verbose_name='Other equipment'),
        ),
    ]
