# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-07 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0078_auto_20200806_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingotherdetails',
            name='other_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Other comments'),
        ),
    ]
