# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-12 01:49
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0080_checklistquestion_application_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalfilmingactivity',
            name='film_purpose',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('education', 'Education'), ('advertising', 'Advertising'), ('feature_film', 'Feature film'), ('recreation', 'Recreation'), ('documentary', 'Documentary'), ('tourism', 'Tourism'), ('other', 'other'), ('social_media', 'Social media/ online content')], max_length=200, null=True, verbose_name='Purpose of Film'),
        ),
    ]
