# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-14 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0083_auto_20200814_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventmanagement',
            name='emergency_response_plan',
            field=models.BooleanField(default=False),
        ),
    ]
