# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0084_proposaleventmanagement_emergency_response_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventotherdetails',
            name='other_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Other comments'),
        ),
    ]
