# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-17 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0085_proposaleventotherdetails_other_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='filming_licence_charge_type',
            field=models.CharField(choices=[('half_day_charge', 'Half day charge'), ('full_day_charge', 'Full day charge'), ('2_days_charge', '2 days charge'), ('3_or_more_days_charge', '3 or more days charge')], default='full_day_charge', max_length=30, verbose_name='Filming Licence charge Type'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='filming_non_standard_charge',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=8),
        ),
    ]
