# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-08-18 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0086_auto_20200817_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='filming_licence_charge_type',
            field=models.CharField(choices=[('half_day_charge', 'Half day charge'), ('full_day_charge', 'Full day charge'), ('2_days_charge', '2 days charge'), ('3_or_more_days_charge', '3 or more days charge'), ('non_standard_charge', 'Non standard charge')], default='full_day_charge', max_length=30, verbose_name='Filming Licence charge Type'),
        ),
    ]
