# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-01 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0088_auto_20200828_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtype',
            name='filming_fee_4days',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='filming_fee_subsequent_day',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='photography_fee_4days',
        ),
        migrations.RemoveField(
            model_name='applicationtype',
            name='photography_fee_subsequent_day',
        ),
        migrations.RemoveField(
            model_name='proposalfilmingactivity',
            name='half_day',
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='filming_fee_2days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming two days fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='filming_fee_3days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Filming 3 days or more fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='photography_fee_2days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography two days fee'),
        ),
        migrations.AddField(
            model_name='applicationtype',
            name='photography_fee_3days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography 3 days or more fee'),
        ),
        migrations.AlterField(
            model_name='applicationtype',
            name='photography_fee_full_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Photography full day fee'),
        ),
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('T Class', 'T Class')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
