# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-23 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0090_auto_20200909_1512'),
        ('commercialoperator', '0089_auto_20200901_1750'),
    ]

    operations = [
    ]
