# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-09-30 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0091_merge_20200923_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposaltype',
            name='name',
            field=models.CharField(choices=[('Commercial operations', 'Commercial operations'), ('Event', 'Event'), ('Filming', 'Filming')], default='T Class', max_length=64, verbose_name='Application name (eg. T Class, Filming, Event, E Class)'),
        ),
    ]
