# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-21 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0092_auto_20200930_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingequipment',
            name='rps_used_details',
            field=models.TextField(blank=True, null=True, verbose_name='RPA used details'),
        ),
    ]
