# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-10-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0095_auto_20201028_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaleventactivities',
            name='event_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Event date'),
        ),
    ]
