# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0096_proposaleventactivities_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OracleCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_type', models.CharField(choices=[('TClass', 'ApplicationType.TCLASS'), ('Filming', 'ApplicationType.FILMING'), ('Event', 'ApplicationType.EVENT')], default='TClass', max_length=64, verbose_name='Application Type')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('archive_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='park',
            name='oracle_code',
        ),
        migrations.AddField(
            model_name='oraclecode',
            name='park',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oracle_code', to='commercialoperator.Park'),
        ),
    ]
