# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-16 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0098_auto_20201116_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalfilmingactivity',
            name='pdswa_location',
            field=models.BooleanField(default=False, verbose_name='Event location within PDSWA'),
        ),
    ]
