# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0099_auto_20201106_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraclecode',
            name='code_type',
            field=models.CharField(choices=[('Commercial operations', 'Commercial operations'), ('Filming', 'Filming'), ('Event', 'Event')], default='Commercial operations', max_length=64, verbose_name='Application Type'),
        ),
        migrations.AlterField(
            model_name='oraclecode',
            name='park',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oracle_codes', to='commercialoperator.Park'),
        ),
    ]
