# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-17 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0099_proposalfilmingactivity_pdswa_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalfilmingactivity',
            name='pdswa_location',
        ),
        migrations.AddField(
            model_name='proposaleventactivities',
            name='pdswa_location',
            field=models.BooleanField(default=False, verbose_name='Event location within PDSWA'),
        ),
    ]
