# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-17 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0100_auto_20201117_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('credit_facility_link', 'Credit Facility Link'), ('deed_poll', 'Deed poll'), ('deed_poll_filming', 'Deed poll Filming'), ('deed_poll_event', 'Deed poll Event'), ('online_training_document', 'Online Training Document'), ('park_finder_link', 'Park Finder Link'), ('fees_and_charges', 'Fees and charges link'), ('commercial_filming_handbook', 'Commercial Filming Handbook link'), ('park_stay_link', 'Park Stay Link'), ('event_traffic_code_of_practice', 'Event traffic code of practice'), ('trail_section_map', 'Trail section map'), ('dwer_application_form', 'DWER Application Form')], max_length=255),
        ),
    ]
