# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-11-25 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0101_auto_20201117_1057'),
        ('commercialoperator', '0100_auto_20201109_1449'),
    ]

    operations = [
    ]
