# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-01-04 07:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commercialoperator', '0102_merge_20201125_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercialoperator_referrals_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
