# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-01-08 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0103_referral_assigned_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='event_training_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersystemsettings',
            name='event_training_completed',
            field=models.BooleanField(default=False),
        ),
    ]
