# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-01-08 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0104_auto_20210108_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='event_training_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersystemsettings',
            name='event_training_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
