# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-01-13 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0105_auto_20210108_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalrequirement',
            name='copied_for_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='require_due_date',
            field=models.BooleanField(default=False),
        ),
    ]
