# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-18 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0130_approval_future_licence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalEmissionStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_standard_type', models.CharField(choices=[('no', 'None'), ('tourism_council', 'Tourism Council WA'), ('eco_tourism', 'Eco Tourism Australia'), ('other', 'Other')], default='no', max_length=40, verbose_name='Emission Standard')),
                ('emission_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalInformationStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_standard_type', models.CharField(choices=[('no', 'None'), ('tourism_council', 'Tourism Council WA'), ('eco_tourism', 'Eco Tourism Australia'), ('other', 'Other')], default='no', max_length=40, verbose_name='Information Standard')),
                ('information_comments', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='key',
            field=models.CharField(choices=[('credit_facility_link', 'Credit Facility Link'), ('deed_poll', 'Deed poll'), ('deed_poll_filming', 'Deed poll Filming'), ('deed_poll_event', 'Deed poll Event'), ('online_training_document', 'Online Training Document'), ('park_finder_link', 'Park Finder Link'), ('fees_and_charges', 'Fees and charges link'), ('event_fees_and_charges', 'Event Fees and charges link'), ('commercial_filming_handbook', 'Commercial Filming Handbook link'), ('park_stay_link', 'Park Stay Link'), ('event_traffic_code_of_practice', 'Event traffic code of practice'), ('trail_section_map', 'Trail section map'), ('dwer_application_form', 'DWER Application Form'), ('tourism_standards_link', 'Tourism Standards Link')], max_length=255),
        ),
        migrations.AddField(
            model_name='proposalinformationstandard',
            name='proposal_other_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_standards', to='commercialoperator.ProposalOtherDetails'),
        ),
        migrations.AddField(
            model_name='proposalemissionstandard',
            name='proposal_other_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_standards', to='commercialoperator.ProposalOtherDetails'),
        ),
    ]
