# Generated by Django 5.0.8 on 2024-11-22 00:08

import commercialoperator.components.bookings.models
import commercialoperator.components.proposals.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ("commercialoperator", "0130_approval_future_licence"),
        ("commercialoperator", "0131_auto_20260318_1153"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DistrictProposalApproverGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_districtproposalapprovergroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DistrictProposalAssessorGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_districtproposalassessorgroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrganisationAccessGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_organisationaccessgroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProposalApproverGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_proposalapprovergroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProposalAssessorGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_proposalassessorgroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QAOfficerGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_qaofficergroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ReferralRecipientGroupMembers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "commercialoperator_referralrecipientgroup_members",
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerOrganisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisation_id",
                    models.IntegerField(
                        unique=True, verbose_name="Ledger Organisation ID"
                    ),
                ),
                (
                    "organisation_name",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=255,
                        verbose_name="Ledger Organisation Name",
                    ),
                ),
                (
                    "organisation_trading_name",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        null=True,
                        verbose_name="Ledger Organisation Trading Name",
                    ),
                ),
                (
                    "organisation_abn",
                    models.CharField(
                        default="",
                        editable=False,
                        max_length=50,
                        verbose_name="Ledger Organisation ABN",
                    ),
                ),
                (
                    "organisation_email",
                    models.EmailField(
                        blank=True,
                        editable=False,
                        max_length=254,
                        null=True,
                        verbose_name="Ledger Organisation Email",
                    ),
                ),
                ("admin_pin_one", models.CharField(blank=True, max_length=50)),
                ("admin_pin_two", models.CharField(blank=True, max_length=50)),
                ("user_pin_one", models.CharField(blank=True, max_length=50)),
                ("user_pin_two", models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name="activitymatrix",
            name="schema",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="approval",
            name="extracted_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approval",
            name="surrender_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="approval",
            name="suspension_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bookinginvoice",
            name="property_cache",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="districtapproval",
            name="extracted_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="districtapproval",
            name="surrender_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="districtapproval",
            name="suspension_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="districtproposal",
            name="proposed_issuance_approval",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="filmingfee",
            name="lines",
            field=models.JSONField(
                default=commercialoperator.components.bookings.models.default_filmingfee_lines
            ),
        ),
        migrations.AlterField(
            model_name="filmingfee",
            name="lines_aggregated",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="assessor_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="comment_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="property_cache",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposed_issuance_approval",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="schema",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="proposalassessmentanswer",
            name="answer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposaleventsparks",
            name="activities_assessor",
            field=models.ManyToManyField(blank=True, to="commercialoperator.activity"),
        ),
        migrations.AlterField(
            model_name="proposaleventstrails",
            name="activities_assessor",
            field=models.ManyToManyField(blank=True, to="commercialoperator.activity"),
        ),
        migrations.AlterField(
            model_name="proposaleventvehiclesvessels",
            name="hired_or_owned",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposalotherdetails",
            name="mooring",
            field=models.JSONField(
                default=commercialoperator.components.proposals.models.default_proposalotherdetails_mooring
            ),
        ),
        migrations.AlterField(
            model_name="proposaltype",
            name="schema",
            field=models.JSONField(
                default=commercialoperator.components.proposals.models.default_proposaltype_schema
            ),
        ),
        migrations.AlterField(
            model_name="taggedproposalapprovergroupactivities",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggedproposalapprovergroupregions",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggedproposalassessorgroupactivities",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
        migrations.AlterField(
            model_name="taggedproposalassessorgroupregions",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_items",
                to="taggit.tag",
            ),
        ),
        migrations.AlterField(
            model_name="usersystemsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="system_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
