# Generated by Django 5.2.12 on 2026-04-10 03:41

import commercialoperator.components.approvals.models
import commercialoperator.components.compliances.models
import commercialoperator.components.organisations.models
import commercialoperator.components.proposals.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0135_alter_licenceperiod_licence_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('surrendered', 'Surrendered'), ('suspended', 'Suspended'), ('extended', 'Extended'), ('awaiting_payment', 'Awaiting Payment')], default='current', max_length=40),
        ),
        migrations.AlterField(
            model_name='approvaldocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.approvals.models.update_approval_doc_filename),
        ),
        migrations.AlterField(
            model_name='approvallogdocument',
            name='_file',
            field=models.FileField(max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.approvals.models.update_approval_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='compliancedocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.compliances.models.update_proposal_complaince_filename),
        ),
        migrations.AlterField(
            model_name='compliancelogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.compliances.models.update_compliance_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='eventsparkdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_events_park_doc_filename),
        ),
        migrations.AlterField(
            model_name='filmingparkdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_filming_park_doc_filename),
        ),
        migrations.AlterField(
            model_name='onholddocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_onhold_doc_filename),
        ),
        migrations.AlterField(
            model_name='organisationlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.organisations.models.update_organisation_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to='organisation/requests/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='organisationrequestlogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.organisations.models.update_organisation_request_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='preeventsparkdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_pre_event_park_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposaldocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_proposal_doc_filename),
        ),
        migrations.AlterField(
            model_name='proposallogdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_proposal_comms_log_filename),
        ),
        migrations.AlterField(
            model_name='proposalrequireddocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_proposal_required_doc_filename),
        ),
        migrations.AlterField(
            model_name='qaofficerdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_qaofficer_doc_filename),
        ),
        migrations.AlterField(
            model_name='referraldocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_referral_doc_filename),
        ),
        migrations.AlterField(
            model_name='requirementdocument',
            name='_file',
            field=models.FileField(max_length=512, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to=commercialoperator.components.proposals.models.update_requirement_doc_filename),
        ),
    ]
