# Generated by Django 5.2.12 on 2026-04-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0136_alter_approval_status_alter_approvaldocument__file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtensionWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The file extension without the dot, e.g. jpg, pdf, docx, etc', max_length=16)),
                ('model', models.CharField(default='all', max_length=255)),
            ],
            options={
                'unique_together': {('name', 'model')},
            },
        ),
    ]
