# Generated by Django 5.2.12 on 2026-04-15 03:05

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0137_fileextensionwhitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrequest',
            name='identification',
            field=models.FileField(blank=True, max_length=512, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/private-media/', location='/data/data/projects/commercialoperator/private-media'), upload_to='organisation/requests'),
        ),
    ]
