# Generated by Django 5.2.12 on 2026-06-22

from django.db import migrations


def add_privacy_policy_url(apps, schema_editor):
    """Add privacy_policy_url to GlobalSettings"""
    GlobalSettings = apps.get_model('commercialoperator', 'GlobalSettings')
    
    # Check if privacy_policy_url already exists
    if not GlobalSettings.objects.filter(key='privacy_policy_url').exists():
        GlobalSettings.objects.create(
            key='privacy_policy_url',
            value='https://www.dbca.wa.gov.au/privacy'
        )


def remove_privacy_policy_url(apps, schema_editor):
    """Remove privacy_policy_url from GlobalSettings"""
    GlobalSettings = apps.get_model('commercialoperator', 'GlobalSettings')
    GlobalSettings.objects.filter(key='privacy_policy_url').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0138_alter_organisationrequest_identification'),
    ]

    operations = [
        migrations.RunPython(add_privacy_policy_url, remove_privacy_policy_url),
    ]
