# Generated by Django 5.2.13 on 2026-05-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0138_alter_organisationrequest_identification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpPage',
        ),
    ]
