# Generated by Django 5.2.13 on 2026-05-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0139_delete_helppage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='property_cache',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
