# Generated by Django 5.2.14 on 2026-06-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commercialoperator', '0139_add_privacy_policy_url'),
        ('commercialoperator', '0140_organisation_property_cache'),
    ]

    operations = [
    ]
